<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topFixedNavbar1" aria-expanded="false"><span class="sr-only">Toggle navigation</span>Menu<span class="glyphicon glyphicon-chevron-down"></span></button>
        <a class="navbar-brand" href="index.php">Dream Betting</a></div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="topFixedNavbar1">
        <ul class="nav navbar-nav">
          <li><a href="index.php">Home<span class="sr-only">(current)</span></a></li>
			<li class="dropdown"><a href="betting" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Betting<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="football.php">Football</a></li>
              <li><a href="baseball.php">Baseball</a></li>
              <li><a href="tennis.php">Tennis</a></li>
				
				<li><a href="cricket.php">Cricket</a></li>
				<li><a href="rugby.php">Rugby</a></li>
             
            </ul>
          </li>
          <li><a href="promotion.php">Promotions</a></li>
			<li><a href="payment.php">Payment <br>methods</a></li>
			<li><a href="privacy.php">Privacy Policy</a></li>
			
			<li><a href="contactus.php">Contact Us</a></li>
          
        </ul>
<ul class="nav navbar-nav navbar-right">
        <li><a href="#">Partners</a></li>
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Social<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">facebook</a></li>
              <li><a href="#">instagram</a></li>
              <li><a href="#">twitter</a></li>
             
            </ul>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <div class="row" id="bet"> </div>
    <!-- /.container-fluid -->
  </nav>
